#/etc/filebeat/filebeat.yml

filebeat.inputs:
  - type: filestream
    id: {{ component_name }}
    enabled: true
    paths:
      - {{ log_file }}
    fields:
      component: {{ component_name }}
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
output.logstash:
  hosts: ["172.31.17.70:5044"]
processors:

#  - drop_fields:
#      fields: ["field1", "field2", ...]
