- name: Install Nginx
  ansible.builtin.yum:
    name: nginx
    state: installed
- name: Copy config file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
- name: Remove html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent
- name: Create html directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory
- name: Download application content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes
- name: Make sure a frontend service is running
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes