
- name: Create app user
  ansible.builtin.user:
    - name: "{{ app_user }}"

- name: Clean up old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: Recreate app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download app content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/{{component_name}}.zip
    dest: /app
    remote_src: yes

