- name: Install Golang
  ansible.builtin.yum:
    name: golang

- name: Set up application Prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install App Dependencies
  ansible.builtin.shell: go mod init {{ component_name }} ;go get; go build
  args:
    chdir: /app

- name: Start Service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml
