- name: Download nodejs rpm
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install nodejs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Set up app prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install npm package
  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: Setup Schema
  ansible.builtin.import_tasks:
    file: setup_schema.yml

- name: Start service
  ansible.builtin.import_tasks:
    file: systemd_setup.yml